services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  server:
    build: server/
    command: python ./server.py
    depends_on:
      - redis
    
  client:
    build: client/
    command: python ./client.py
    depends_on:
      - server